// ── QOR llguidance Bridge — Phase 5 ─────────────────────────────────────
//
// This module will connect QOR's reasoning engine to LLMs via llguidance.
// The LLM provides natural language understanding and hypothesis generation;
// QOR provides structured reasoning, truth values, and belief revision.
//
// Flow:
//   Natural language → LLM + llguidance → QOR neurons
//   QOR neurons → LLM + llguidance → Natural language explanation
//   QOR knowledge gaps → LLM hypotheses → QOR evaluates + revises

use std::collections::HashMap;

use qor_core::neuron::{Condition, Neuron, Statement};
use qor_core::truth_value::TruthValue;

/// Configuration for LLM-guided reasoning.
#[derive(Debug, Clone)]
pub struct GuidanceConfig {
    /// Maximum tokens for LLM generation.
    pub max_tokens: usize,
    /// Temperature for LLM sampling (0.0 = deterministic, 1.0 = creative).
    pub temperature: f64,
    /// Minimum confidence for accepting LLM-generated hypotheses.
    pub min_confidence: f64,
}

impl Default for GuidanceConfig {
    fn default() -> Self {
        GuidanceConfig {
            max_tokens: 256,
            temperature: 0.3,
            min_confidence: 0.5,
        }
    }
}

/// A hypothesis generated by the LLM for QOR to evaluate.
#[derive(Debug, Clone)]
pub struct Hypothesis {
    /// The QOR statement proposed by the LLM.
    pub statement: Statement,
    /// Estimated truth value (LLM's confidence in this hypothesis).
    pub estimated_tv: TruthValue,
    /// Natural language explanation of why this might be true.
    pub rationale: String,
}

/// Result of an LLM-guided reasoning session.
#[derive(Debug)]
pub struct GuidanceResult {
    /// Hypotheses generated by the LLM.
    pub hypotheses: Vec<Hypothesis>,
    /// Natural language summary of findings.
    pub summary: String,
}

/// Convert natural language to QOR statements via LLM + llguidance.
///
/// Phase 5: Not yet implemented.
pub fn nl_to_qor(_text: &str, _config: &GuidanceConfig) -> Result<Vec<Statement>, String> {
    Err("Phase 5: llguidance integration not yet implemented".into())
}

/// Convert QOR statements to natural language explanation via LLM.
///
/// Phase 5: Not yet implemented.
pub fn qor_to_nl(_statements: &[Statement], _config: &GuidanceConfig) -> Result<String, String> {
    Err("Phase 5: llguidance integration not yet implemented".into())
}

/// Generate hypotheses about knowledge gaps using LLM reasoning.
///
/// Phase 5: Not yet implemented.
pub fn generate_hypotheses(
    _knowledge: &[Statement],
    _config: &GuidanceConfig,
) -> Result<GuidanceResult, String> {
    Err("Phase 5: llguidance integration not yet implemented".into())
}

// ── Natural Language Summary (template-based, no LLM needed) ─────────

/// Generate a natural language summary of brain knowledge.
///
/// Template-based — reads QOR facts and produces readable English.
/// No LLM required. Works entirely from the stored knowledge.
pub fn summarize(statements: &[Statement]) -> String {
    let mut lines = Vec::new();
    lines.push("  ~~~ QOR Brain Summary ~~~".to_string());
    lines.push(String::new());

    // Collect info from statements
    let meanings = collect_meanings(statements);
    let domain = find_domain(statements);
    let data_points = find_data_points(statements);

    // Domain
    if let Some(d) = &domain {
        lines.push(format!("  Domain: {}", d));
    }
    if let Some(dp) = data_points {
        lines.push(format!("  Data points: {}", dp));
    }
    lines.push(String::new());

    // Stats
    let stats = summarize_stats(statements);
    if !stats.is_empty() {
        lines.push("  Statistics:".to_string());
        for s in &stats {
            lines.push(format!("    {}", s));
        }
        lines.push(String::new());
    }

    // Pattern rates
    let rates = summarize_pattern_rates(statements, &meanings);
    if !rates.is_empty() {
        lines.push("  Patterns:".to_string());
        for r in &rates {
            lines.push(format!("    {}", r));
        }
        lines.push(String::new());
    }

    // Co-occurrences
    let cooccur = summarize_co_occurrences(statements);
    if !cooccur.is_empty() {
        lines.push("  Co-occurrences:".to_string());
        for c in &cooccur {
            lines.push(format!("    {}", c));
        }
        lines.push(String::new());
    }

    // Rules
    let rules = summarize_rules(statements);
    if !rules.is_empty() {
        lines.push("  Learned Rules:".to_string());
        for r in &rules {
            lines.push(format!("    {}", r));
        }
        lines.push(String::new());
    }

    lines.join("\n")
}

/// Collect `(meaning pattern description)` facts.
fn collect_meanings(statements: &[Statement]) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for stmt in statements {
        if let Statement::Fact { neuron, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() == 3 {
                    if let (Neuron::Symbol(pred), Neuron::Symbol(key), Neuron::Symbol(val)) =
                        (&parts[0], &parts[1], &parts[2])
                    {
                        if pred == "meaning" {
                            map.insert(key.clone(), val.replace('-', " "));
                        }
                    }
                }
            }
        }
    }
    map
}

/// Find `(domain X)` fact.
fn find_domain(statements: &[Statement]) -> Option<String> {
    for stmt in statements {
        if let Statement::Fact { neuron, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() == 2 {
                    if let (Neuron::Symbol(pred), Neuron::Symbol(val)) = (&parts[0], &parts[1]) {
                        if pred == "domain" {
                            return Some(val.clone());
                        }
                    }
                }
            }
        }
    }
    None
}

/// Find `(data-points N)` fact.
fn find_data_points(statements: &[Statement]) -> Option<String> {
    for stmt in statements {
        if let Statement::Fact { neuron, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() == 2 {
                    if let (Neuron::Symbol(pred), Neuron::Symbol(val)) = (&parts[0], &parts[1]) {
                        if pred == "data-points" {
                            return Some(val.clone());
                        }
                    }
                }
            }
        }
    }
    None
}

/// Summarize stat-X facts into readable strings.
fn summarize_stats(statements: &[Statement]) -> Vec<String> {
    // Group stats by predicate
    let mut stats: HashMap<String, HashMap<String, String>> = HashMap::new();

    for stmt in statements {
        if let Statement::Fact { neuron, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() == 3 {
                    if let Neuron::Symbol(pred) = &parts[0] {
                        if pred.starts_with("stat-") {
                            let indicator = pred.strip_prefix("stat-").unwrap_or(pred);
                            if let Neuron::Symbol(stat_type) = &parts[1] {
                                let val = format!("{}", parts[2]);
                                stats
                                    .entry(indicator.to_string())
                                    .or_default()
                                    .insert(stat_type.clone(), val);
                            }
                        }
                    }
                }
            }
        }
    }

    let mut result = Vec::new();
    let mut sorted: Vec<_> = stats.into_iter().collect();
    sorted.sort_by_key(|(name, _)| name.clone());

    for (indicator, vals) in sorted {
        let mut parts = Vec::new();
        if let Some(mean) = vals.get("mean") {
            parts.push(format!("average: {}", mean));
        }
        if let Some(count) = vals.get("count") {
            parts.push(format!("{} observations", count));
        }
        if !parts.is_empty() {
            result.push(format!("{}: {}", indicator, parts.join(", ")));
        }
    }
    result
}

/// Summarize pattern-rate facts with meanings.
fn summarize_pattern_rates(statements: &[Statement], meanings: &HashMap<String, String>) -> Vec<String> {
    let mut result = Vec::new();

    for stmt in statements {
        if let Statement::Fact { neuron, tv, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() >= 4 {
                    if let Neuron::Symbol(pred) = &parts[0] {
                        if pred == "pattern-rate" {
                            if let (Neuron::Symbol(pattern), count, total) =
                                (&parts[1], &parts[2], &parts[3])
                            {
                                let count_val = count.as_f64().unwrap_or(0.0) as usize;
                                let total_val = total.as_f64().unwrap_or(1.0) as usize;
                                let pct = if total_val > 0 {
                                    count_val as f64 / total_val as f64 * 100.0
                                } else {
                                    0.0
                                };

                                let meaning_desc = meanings
                                    .get(pattern.as_str())
                                    .map(|m| format!(" ({})", m))
                                    .unwrap_or_default();

                                let tv_str = tv
                                    .map(|t| format!(" {}", t))
                                    .unwrap_or_default();

                                result.push(format!(
                                    "{} occurs in {:.0}% of observations{}{}",
                                    pattern, pct, meaning_desc, tv_str
                                ));
                            }
                        }
                    }
                }
            }
        }
    }
    result
}

/// Summarize co-occurrence facts (>=50% strength).
fn summarize_co_occurrences(statements: &[Statement]) -> Vec<String> {
    let mut result = Vec::new();

    for stmt in statements {
        if let Statement::Fact { neuron, tv, .. } = stmt {
            if let Neuron::Expression(parts) = neuron {
                if parts.len() >= 5 {
                    if let Neuron::Symbol(pred) = &parts[0] {
                        if pred == "co-occur" {
                            if let (Neuron::Symbol(a), Neuron::Symbol(b)) = (&parts[1], &parts[2]) {
                                let strength = tv.map(|t| t.strength).unwrap_or(0.0);
                                if strength >= 0.50 {
                                    let pct = (strength * 100.0).round() as usize;
                                    result.push(format!(
                                        "When {}, {}% of the time also {}",
                                        a, pct, b
                                    ));
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    result
}

/// Summarize rules in natural language.
fn summarize_rules(statements: &[Statement]) -> Vec<String> {
    let mut result = Vec::new();

    for stmt in statements {
        if let Statement::Rule { head, body, tv } = stmt {
            let body_parts: Vec<String> = body.iter().map(|c| match c {
                Condition::Positive(n) => format!("{}", n),
                Condition::Negated(n) => format!("not {}", n),
                Condition::Guard(op, lhs, rhs) => {
                    let op_str = match op {
                        qor_core::neuron::ComparisonOp::Gt => ">",
                        qor_core::neuron::ComparisonOp::Lt => "<",
                        qor_core::neuron::ComparisonOp::Ge => ">=",
                        qor_core::neuron::ComparisonOp::Le => "<=",
                        qor_core::neuron::ComparisonOp::Eq => "==",
                        qor_core::neuron::ComparisonOp::Ne => "!=",
                    };
                    format!("({} {} {})", op_str, lhs, rhs)
                }
                Condition::Aggregate { op, pattern, bind_var, result_var } => {
                    format!("({} {} ${} -> ${})", op, pattern, bind_var, result_var)
                }
                Condition::Arithmetic { op, lhs, rhs, result_var } => {
                    format!("({} {} {} ${})", op, lhs, rhs, result_var)
                }
                Condition::NegatedPresent(n) => format!("not-present {}", n),
                Condition::Lookup { predicate, subject, result_var } => {
                    format!("(lookup \"{}\" {} ${})", predicate, subject, result_var)
                }
                Condition::EndsWith(n, d) => format!("(ends-with {} {})", n, d),
            }).collect();
            let tv_str = tv
                .map(|t| format!(" {}", t))
                .unwrap_or_default();
            result.push(format!(
                "{} when {}{}",
                head,
                body_parts.join(" and "),
                tv_str
            ));
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use qor_core::neuron::QorValue;

    #[test]
    fn test_guidance_config_defaults() {
        let cfg = GuidanceConfig::default();
        assert_eq!(cfg.max_tokens, 256);
        assert!((cfg.temperature - 0.3).abs() < 0.01);
        assert!((cfg.min_confidence - 0.5).abs() < 0.01);
    }

    #[test]
    fn test_summarize_stats() {
        let stmts = vec![
            Statement::Fact {
                neuron: Neuron::Expression(vec![
                    Neuron::Symbol("stat-close".into()),
                    Neuron::Symbol("mean".into()),
                    Neuron::Value(QorValue::Float(88075.0)),
                ]),
                tv: Some(TruthValue::new(0.99, 0.99)),
                decay: None,
            },
            Statement::Fact {
                neuron: Neuron::Expression(vec![
                    Neuron::Symbol("stat-close".into()),
                    Neuron::Symbol("count".into()),
                    Neuron::Value(QorValue::Int(10000)),
                ]),
                tv: Some(TruthValue::new(0.99, 0.99)),
                decay: None,
            },
        ];

        let summary = summarize(&stmts);
        assert!(summary.contains("close"), "should mention indicator name");
        assert!(summary.contains("88075"), "should include mean value");
        assert!(summary.contains("10000"), "should include count");
    }

    #[test]
    fn test_summarize_pattern_rates_with_meanings() {
        let stmts = vec![
            Statement::Fact {
                neuron: Neuron::Expression(vec![
                    Neuron::Symbol("meaning".into()),
                    Neuron::Symbol("overbought".into()),
                    Neuron::Symbol("buying-pressure-extreme".into()),
                ]),
                tv: Some(TruthValue::new(0.99, 0.99)),
                decay: None,
            },
            Statement::Fact {
                neuron: Neuron::Expression(vec![
                    Neuron::Symbol("pattern-rate".into()),
                    Neuron::Symbol("overbought".into()),
                    Neuron::Value(QorValue::Int(40)),
                    Neuron::Value(QorValue::Int(1000)),
                ]),
                tv: Some(TruthValue::new(0.04, 0.90)),
                decay: None,
            },
        ];

        let summary = summarize(&stmts);
        assert!(summary.contains("overbought"), "should mention pattern");
        assert!(summary.contains("4%"), "should show percentage");
        assert!(summary.contains("buying pressure extreme"), "should include meaning");
    }

    #[test]
    fn test_summarize_co_occurrences() {
        let stmts = vec![
            Statement::Fact {
                neuron: Neuron::Expression(vec![
                    Neuron::Symbol("co-occur".into()),
                    Neuron::Symbol("overbought".into()),
                    Neuron::Symbol("trending".into()),
                    Neuron::Value(QorValue::Int(80)),
                    Neuron::Value(QorValue::Int(100)),
                ]),
                tv: Some(TruthValue::new(0.80, 0.95)),
                decay: None,
            },
        ];

        let summary = summarize(&stmts);
        assert!(summary.contains("overbought"), "should mention first pattern");
        assert!(summary.contains("trending"), "should mention second pattern");
        assert!(summary.contains("80%"), "should show co-occurrence rate");
    }

    #[test]
    fn test_stubs_return_phase5_error() {
        let cfg = GuidanceConfig::default();
        assert!(nl_to_qor("hello", &cfg).is_err());
        assert!(qor_to_nl(&[], &cfg).is_err());
        assert!(generate_hypotheses(&[], &cfg).is_err());

        let err = nl_to_qor("test", &cfg).unwrap_err();
        assert!(err.contains("Phase 5"));
    }
}
